// District → thana/upazila map for Bangladesh address selectors.
// Shared so multiple forms (orders, competition registration) stay in sync.
export const BD_LOCATIONS = {
  Bagerhat: [
    "Fakirhat",
    "Bagerhat Sadar",
    "Mollahat",
    "Sarankhola",
    "Rampal",
    "Morrelganj",
    "Kachua",
    "Mongla",
    "Chitalmari",
  ],
  Bandarban: [
    "Bandarban Sadar",
    "Alikadam",
    "Naikhongchhari",
    "Rowangchhari",
    "Lama",
    "Ruma",
    "Thanchi",
  ],
  Barguna: ["Amtali", "Barguna Sadar", "Betagi", "Bamna", "Pathorghata", "Taltali"],
  Barisal: [
    "Barisal Sadar",
    "Bakerganj",
    "Babuganj",
    "Wazirpur",
    "Banaripara",
    "Gournadi",
    "Agailjhara",
    "Mehendiganj",
    "Muladi",
    "Hizla",
    "Barishal City Corporation",
  ],
  Bhola: [
    "Bhola Sadar",
    "Borhanuddin",
    "Charfesson",
    "Doulatkhan",
    "Monpura",
    "Tazumuddin",
    "Lalmohan",
  ],
  Bogura: [
    "Kahaloo",
    "Bogra Sadar",
    "Shariakandi",
    "Shajahanpur",
    "Dupchanchia",
    "Adamdighi",
    "Nondigram",
    "Sonatala",
    "Dhunot",
    "Gabtali",
    "Sherpur",
    "Shibganj",
  ],
  Brahmanbaria: [
    "Brahmanbaria Sadar",
    "Kasba",
    "Nasirnagar",
    "Sarail",
    "Ashuganj",
    "Akhaura",
    "Nabinagar",
    "Bancharampur",
    "Bijoynagar",
  ],
  Chandpur: [
    "Haimchar",
    "Kachua",
    "Shahrasti",
    "Chandpur Sadar",
    "Matlab South",
    "Hajiganj",
    "Matlab North",
    "Faridgonj",
  ],
  "Chapai Nawabganj": [
    "Chapainawabganj Sadar",
    "Gomostapur",
    "Nachol",
    "Bholahat",
    "Shibganj",
  ],
  Chattogram: [
    "Rangunia",
    "Sitakunda",
    "Mirsharai",
    "Patiya",
    "Sandwip",
    "Banshkhali",
    "Boalkhali",
    "Anwara",
    "Chandanaish",
    "Satkania",
    "Lohagara",
    "Hathazari",
    "Fatikchhari",
    "Raozan",
    "Karnafuli",
    "Chittagong City Corporation",
  ],
  Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  "Cox's Bazar": [
    "Coxsbazar Sadar",
    "Chakaria",
    "Kutubdia",
    "Ukhiya",
    "Moheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
  ],
  Cumilla: [
    "Debidwar",
    "Barura",
    "Brahmanpara",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Homna",
    "Laksam",
    "Muradnagar",
    "Nangalkot",
    "Comilla Sadar",
    "Meghna",
    "Monohargonj",
    "Sadarsouth",
    "Titas",
    "Burichang",
    "Lalmai",
    "Cumilla City Corporation",
  ],
  "Dhaka City": [
    "Adabor",
    "Badda",
    "Banani",
    "Bangshal",
    "Bhashantek",
    "Biman Bandar",
    "Cantonment",
    "Chawkbazar",
    "Dakshinkhan",
    "Darus Salam",
    "Demra",
    "Dhanmondi",
    "Gendaria",
    "Gulshan",
    "Hatirjheel",
    "Hazaribagh",
    "Jatrabari",
    "Kadamtali",
    "Kafrul",
    "Kalabagan",
    "Kamrangirchar",
    "Khilgaon",
    "Khilkhet",
    "Kotwali",
    "Lalbagh",
    "Mirpur",
    "Mohammadpur",
    "Motijheel",
    "Mugda",
    "New Market",
    "Pallabi",
    "Paltan",
    "Ramna",
    "Rampura",
    "Rupnagar",
    "Sabujbagh",
    "Shah Ali",
    "Shahbagh",
    "Shahjahanpur",
    "Sher-e-Bangla Nagar",
    "Shyampur",
    "Sutrapur",
    "Tejgaon",
    "Tejgaon Industrial Area",
    "Turag",
    "Uttara East",
    "Uttara West",
    "Uttarkhan",
    "Vatara",
    "Wari",
  ],
  "Dhaka Sub-Urban": [
    "Ashulia",
    "Dhamrai",
    "Dohar",
    "Hemayetpur",
    "Keraniganj Model",
    "Nawabganj",
    "Savar",
    "South Keraniganj",
  ],
  Dinajpur: [
    "Nawabganj",
    "Birganj",
    "Ghoraghat",
    "Birampur",
    "Parbatipur",
    "Bochaganj",
    "Kaharol",
    "Fulbari",
    "Dinajpur Sadar",
    "Hakimpur",
    "Khansama",
    "Birol",
    "Chirirbandar",
  ],
  Faridpur: [
    "Faridpur Sadar",
    "Alfadanga",
    "Boalmari",
    "Sadarpur",
    "Nagarkanda",
    "Bhanga",
    "Charbhadrasan",
    "Madhukhali",
    "Saltha",
  ],
  Feni: [
    "Chhagalnaiya",
    "Feni Sadar",
    "Sonagazi",
    "Fulgazi",
    "Parshuram",
    "Daganbhuiyan",
  ],
  Gaibandha: [
    "Sadullapur",
    "Gaibandha Sadar",
    "Palashbari",
    "Saghata",
    "Gobindaganj",
    "Sundarganj",
    "Phulchari",
  ],
  Gazipur: [
    "Kaliganj",
    "Kaliakair",
    "Kapasia",
    "Gazipur Sadar",
    "Sreepur",
    "Gazipur City Corporation",
  ],
  Gopalganj: ["Gopalganj Sadar", "Kashiani", "Tungipara", "Kotalipara", "Muksudpur"],
  Habiganj: [
    "Nabiganj",
    "Bahubal",
    "Ajmiriganj",
    "Baniachong",
    "Lakhai",
    "Chunarughat",
    "Habiganj Sadar",
    "Madhabpur",
    "Shayestagonj",
  ],
  Jamalpur: [
    "Jamalpur Sadar",
    "Melandah",
    "Islampur",
    "Dewangonj",
    "Sarishabari",
    "Madarganj",
    "Bokshiganj",
  ],
  Jashore: [
    "Manirampur",
    "Abhaynagar",
    "Bagherpara",
    "Chougachha",
    "Jhikargacha",
    "Keshabpur",
    "Jessore Sadar",
    "Sharsha",
  ],
  Jhalokati: ["Jhalakathi Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Jhenaidah: [
    "Jhenaidah Sadar",
    "Shailkupa",
    "Harinakundu",
    "Kaliganj",
    "Kotchandpur",
    "Moheshpur",
  ],
  Joypurhat: ["Akkelpur", "Kalai", "Khetlal", "Panchbibi", "Joypurhat Sadar"],
  Khagrachhari: [
    "Khagrachhari Sadar",
    "Dighinala",
    "Panchari",
    "Laxmichhari",
    "Mohalchari",
    "Manikchari",
    "Ramgarh",
    "Matiranga",
    "Guimara",
  ],
  Khulna: [
    "Paikgasa",
    "Fultola",
    "Digholia",
    "Rupsha",
    "Terokhada",
    "Dumuria",
    "Botiaghata",
    "Dakop",
    "Koyra",
    "Khulna City Corporation",
  ],
  Kishoreganj: [
    "Itna",
    "Katiadi",
    "Bhairab",
    "Tarail",
    "Hossainpur",
    "Pakundia",
    "Kuliarchar",
    "Kishoreganj Sadar",
    "Karimgonj",
    "Bajitpur",
    "Austagram",
    "Mithamoin",
    "Nikli",
  ],
  Kurigram: [
    "Kurigram Sadar",
    "Nageshwari",
    "Bhurungamari",
    "Phulbari",
    "Rajarhat",
    "Ulipur",
    "Chilmari",
    "Rowmari",
    "Charrajibpur",
  ],
  Kushtia: [
    "Kushtia Sadar",
    "Kumarkhali",
    "Khoksa",
    "Mirpur",
    "Daulatpur",
    "Bheramara",
  ],
  Lakshmipur: ["Lakshmipur Sadar", "Kamalnagar", "Raipur", "Ramgati", "Ramganj"],
  Lalmonirhat: [
    "Lalmonirhat Sadar",
    "Kaliganj",
    "Hatibandha",
    "Patgram",
    "Aditmari",
  ],
  Madaripur: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir"],
  Magura: ["Shalikha", "Sreepur", "Magura Sadar", "Mohammadpur"],
  Manikganj: [
    "Harirampur",
    "Saturia",
    "Manikganj Sadar",
    "Gior",
    "Shibaloy",
    "Doulatpur",
    "Singiar",
  ],
  Meherpur: ["Mujibnagar", "Meherpur Sadar", "Gangni"],
  Moulvibazar: [
    "Barlekha",
    "Kamolganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
    "Juri",
  ],
  Munshiganj: [
    "Munshiganj Sadar",
    "Sreenagar",
    "Sirajdikhan",
    "Louhajanj",
    "Gajaria",
    "Tongibari",
  ],
  Mymensingh: [
    "Fulbaria",
    "Trishal",
    "Bhaluka",
    "Muktagacha",
    "Mymensingh Sadar",
    "Dhobaura",
    "Phulpur",
    "Haluaghat",
    "Gouripur",
    "Gafargaon",
    "Iswarganj",
    "Nandail",
    "Tarakanda",
    "Mymensingh City Corporation",
  ],
  Narayanganj: [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
    "Narayanganj City Corporation",
  ],
  Narsingdi: [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  Natore: [
    "Natore Sadar",
    "Singra",
    "Baraigram",
    "Bagatipara",
    "Lalpur",
    "Gurudaspur",
    "Naldanga",
  ],
  Naogaon: [
    "Mohadevpur",
    "Badalgachi",
    "Patnitala",
    "Dhamoirhat",
    "Niamatpur",
    "Manda",
    "Atrai",
    "Raninagar",
    "Naogaon Sadar",
    "Porsha",
    "Sapahar",
  ],
  Netrokona: [
    "Barhatta",
    "Durgapur",
    "Kendua",
    "Atpara",
    "Madan",
    "Khaliajuri",
    "Kalmakanda",
    "Mohongonj",
    "Purbadhala",
    "Netrokona Sadar",
  ],
  Nilphamari: [
    "Syedpur",
    "Domar",
    "Dimla",
    "Jaldhaka",
    "Kishorganj",
    "Nilphamari Sadar",
  ],
  Noakhali: [
    "Noakhali Sadar",
    "Companiganj",
    "Begumganj",
    "Hatia",
    "Subarnachar",
    "Kabirhat",
    "Senbug",
    "Chatkhil",
    "Sonaimori",
  ],
  Pabna: [
    "Sujanagar",
    "Ishurdi",
    "Bhangura",
    "Pabna Sadar",
    "Bera",
    "Atghoria",
    "Chatmohar",
    "Santhia",
    "Faridpur",
  ],
  Panchagarh: ["Panchagarh Sadar", "Debiganj", "Boda", "Atwari", "Tetulia"],
  Patuakhali: [
    "Bauphal",
    "Patuakhali Sadar",
    "Dumki",
    "Dashmina",
    "Kalapara",
    "Mirzaganj",
    "Galachipa",
    "Rangabali",
  ],
  Pirojpur: [
    "Pirojpur Sadar",
    "Nazirpur",
    "Kawkhali",
    "Zianagar",
    "Bhandaria",
    "Mathbaria",
    "Nesarabad",
  ],
  Rajbari: ["Rajbari Sadar", "Goalanda", "Pangsa", "Baliakandi", "Kalukhali"],
  Rajshahi: [
    "Paba",
    "Durgapur",
    "Mohonpur",
    "Charghat",
    "Puthia",
    "Bagha",
    "Godagari",
    "Tanore",
    "Bagmara",
    "Rajshahi City Corporation",
  ],
  Rangamati: [
    "Rangamati Sadar",
    "Kaptai",
    "Kawkhali",
    "Baghaichari",
    "Barkal",
    "Langadu",
    "Rajasthali",
    "Belaichari",
    "Juraichari",
    "Naniarchar",
  ],
  Rangpur: [
    "Rangpur Sadar",
    "Gangachara",
    "Taragonj",
    "Badargonj",
    "Mithapukur",
    "Pirgonj",
    "Kaunia",
    "Pirgacha",
    "Rangpur City Corporation",
  ],
  Satkhira: [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala",
    "Kaliganj",
  ],
  Shariatpur: [
    "Shariatpur Sadar",
    "Naria",
    "Zajira",
    "Gosairhat",
    "Bhedarganj",
    "Damudya",
  ],
  Sherpur: ["Sherpur Sadar", "Nalitabari", "Sreebordi", "Nokla", "Jhenaigati"],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhand",
    "Kazipur",
    "Raigonj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullapara",
  ],
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Sylhet Sadar",
    "Zakiganj",
    "Dakshinsurma",
    "Osmaninagar",
    "Sylhet City Corporation",
  ],
  Sunamganj: [
    "Sunamganj Sadar",
    "South Sunamganj",
    "Bishwambarpur",
    "Chhatak",
    "Jagannathpur",
    "Dowarabazar",
    "Tahirpur",
    "Dharmapasha",
    "Jamalganj",
    "Shalla",
    "Derai",
  ],
  Tangail: [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Ghatail",
    "Gopalpur",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
    "Kalihati",
    "Dhanbari",
  ],
  Thakurgaon: [
    "Thakurgaon Sadar",
    "Pirganj",
    "Ranisankail",
    "Haripur",
    "Baliadangi",
  ],
};

export const DISTRICTS = Object.keys(BD_LOCATIONS);
